name: Release To Maven

# Run workflow on commits to the `master` branch
on:
   workflow_dispatch:
    inputs:
      Version:
        description: "Version to be released in format: x.y.z, where x => major version, y => minor version and z => patch version"
        required: true
        default: "0.1.0"
      Title:
        description: "Title of the release"
        required: true
        default: "Improving API developer experience"

jobs:
  publish:
    name: Creating release version
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: Update version in pom.xml (Release only)
        run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.Version }} -DgenerateBackupPoms=false
        
      - name: Run the Action
        if: steps.release.outputs.exit_code == 0
        uses: devops-infra/action-commit-push@master
        with:
           github_token: "${{ secrets.TOKEN_GITHUB }}"
           add_timestamp: true
           commit_message: "Update pom.xml"
           force: false
           target_branch: ${{ github.ref }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN_GITHIB }}
          commit-message: Release version
          signoff: false
          branch: project-version-update
          delete-branch: true
          title: '[Release To maven] Update POM'
          body: |
            Update report
            - Updated with *today's* date

          labels: |
            automated pr
          assignees: hamza94shoukat
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
    
