name: Release To Maven
run-name: ${{ github.event.inputs.Title }} (${{ github.event.inputs.Version }})
on:
  workflow_dispatch:
    inputs:
      Version:
        description: "Version to be released in format: x.y.z, where x => major version, y => minor version and z => patch version"
        required: true
        default: "0.1.0"
      Title:
        description: "Title of the release"
        required: true
        default: "Improving API developer experience"

jobs:
  publish:
    name: Creating release version ${{ github.event.inputs.Version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: maven
          server-id: ossrh
          settings-path: ${{ github.workspace }}
          server-username: MAVEN_USERNAME
          server-password: GR911m31GR911m31!
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: build artifact
        run: mvn clean package
      - name: Create Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          custom_tag: ${{ github.event.inputs.Version }}
          tag_prefix: ""
          
      - name: Create release
        uses: ncipollo/release-action@v1
        with: 
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ github.event.inputs.Title }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Publish to the Maven Central Repository
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
