name: Release To Maven
on:
  workflow_dispatch
   
jobs:
  publish:
    name: Creating release version
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: maven
          server-id: ossrh
          settings-path: ${{ github.workspace }}
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase:  ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: build artifact
        run: mvn clean package
      - id: install-secret-key
        name: Install gpg secret key
        run: 'echo "${{ secrets.OSSRH_USERNAME }}" > username'
        shell: bash
      - name: Publish to the Maven Central Repository
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            clean deploy
